#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Apr 27 16:38:00 CEST 2026
maven-metadata-jitpack.io.xml.error=
maven-metadata-jitpack.io.xml.lastUpdated=1777300680108
maven-metadata-minecraft-repo.xml.error=
maven-metadata-minecraft-repo.xml.lastUpdated=1777300680113
maven-metadata-papermc.xml.lastUpdated=1777300680095
maven-metadata-placeholderapi.xml.error=
maven-metadata-placeholderapi.xml.lastUpdated=1777300680103
maven-metadata-spigot-repo.xml.lastUpdated=1777300680096
