#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Apr 27 16:37:45 CEST 2026
maven-metadata-jitpack.io.xml.error=
maven-metadata-jitpack.io.xml.lastUpdated=1777300665872
maven-metadata-minecraft-repo.xml.error=
maven-metadata-minecraft-repo.xml.lastUpdated=1777300665876
maven-metadata-papermc.xml.lastUpdated=1777300665859
maven-metadata-placeholderapi.xml.error=
maven-metadata-placeholderapi.xml.lastUpdated=1777300665867
maven-metadata-spigot-repo.xml.error=
maven-metadata-spigot-repo.xml.lastUpdated=1777300665860
